// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type AlembicVersion struct {
	VersionNum string `json:"version_num"`
}

type AnswerExplanation struct {
	ID              int32  `json:"id"`
	RepliQuestionID int32  `json:"repli_question_id"`
	Explanation     string `json:"explanation"`
}

type Choice struct {
	ID         int32  `json:"id"`
	QuestionID int32  `json:"question_id"`
	Letter     string `json:"letter"`
	Answer     string `json:"answer"`
}

type GooseDbVersion struct {
	ID        int32     `json:"id"`
	VersionID int64     `json:"version_id"`
	IsApplied bool      `json:"is_applied"`
	Tstamp    time.Time `json:"tstamp"`
}

type Question struct {
	ID                   int32         `json:"id"`
	SubjectID            int32         `json:"subject_id"`
	TopicID              int32         `json:"topic_id"`
	Question             string        `json:"question"`
	NeedsReference       bool          `json:"needs_reference"`
	ReferenceDescription string        `json:"reference_description"`
	CorrectChoiceID      sql.NullInt32 `json:"correct_choice_id"`
	SourceID             int32         `json:"source_id"`
}

type RepliChoice struct {
	ID              int32  `json:"id"`
	RepliQuestionID int32  `json:"repli_question_id"`
	Letter          string `json:"letter"`
	Answer          string `json:"answer"`
}

type RepliQuestion struct {
	ID                     int32          `json:"id"`
	FromQuestionID         int32          `json:"from_question_id"`
	LevelOfDifficulty      int32          `json:"level_of_difficulty"`
	Question               string         `json:"question"`
	CorrectChoiceID        sql.NullInt32  `json:"correct_choice_id"`
	IsAnAcceptableQuestion bool           `json:"is_an_acceptable_question"`
	RefinedQuestion        sql.NullString `json:"refined_question"`
	AnsExplanation         sql.NullString `json:"ans_explanation"`
}

type Source struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Subject struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Topic struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}
