// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repli _questions.sql

package db

import (
	"context"
	"database/sql"
)

const listRepliQuestionsWithChoices = `-- name: ListRepliQuestionsWithChoices :many
SELECT
    rq.id AS question_id,
    rq.from_question_id,
    rq.level_of_difficulty,
    rq.question,
    rq.correct_choice_id,
    rq.is_a_complete_question,
    rq.refined_question,

    rc.id AS choice_id,
    rc.letter AS choice_letter,
    rc.answer AS choice_answer,

    cc.letter AS correct_choice_letter,
    cc.answer AS correct_choice_answer
FROM repli_questions rq
         JOIN repli_choices rc
              ON rc.repli_question_id = rq.id
         LEFT JOIN repli_choices cc
                   ON cc.id = rq.correct_choice_id
ORDER BY rq.id, rc.letter
`

type ListRepliQuestionsWithChoicesRow struct {
	QuestionID          int32          `json:"question_id"`
	FromQuestionID      int32          `json:"from_question_id"`
	LevelOfDifficulty   int32          `json:"level_of_difficulty"`
	Question            string         `json:"question"`
	CorrectChoiceID     sql.NullInt32  `json:"correct_choice_id"`
	IsACompleteQuestion bool           `json:"is_a_complete_question"`
	RefinedQuestion     sql.NullString `json:"refined_question"`
	ChoiceID            int32          `json:"choice_id"`
	ChoiceLetter        string         `json:"choice_letter"`
	ChoiceAnswer        string         `json:"choice_answer"`
	CorrectChoiceLetter sql.NullString `json:"correct_choice_letter"`
	CorrectChoiceAnswer sql.NullString `json:"correct_choice_answer"`
}

func (q *Queries) ListRepliQuestionsWithChoices(ctx context.Context) ([]ListRepliQuestionsWithChoicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRepliQuestionsWithChoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRepliQuestionsWithChoicesRow
	for rows.Next() {
		var i ListRepliQuestionsWithChoicesRow
		if err := rows.Scan(
			&i.QuestionID,
			&i.FromQuestionID,
			&i.LevelOfDifficulty,
			&i.Question,
			&i.CorrectChoiceID,
			&i.IsACompleteQuestion,
			&i.RefinedQuestion,
			&i.ChoiceID,
			&i.ChoiceLetter,
			&i.ChoiceAnswer,
			&i.CorrectChoiceLetter,
			&i.CorrectChoiceAnswer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
